---
title: "ggplot2 training"
author: "Arkadi Avanesyan"
date: "March 9 2022"
output:
  html_document: default
  pdf_document: default
---

```{r warning = FALSE, message = FALSE}
options(scipen = 999) #show all decimal points
library(dplyr)
library(tidyr)
library(ggplot2)
library(rmarkdown)
library(openxlsx)
library(kableExtra)
```

### ggplot2 basics

```{r}
sample_data <- tibble(
  Month = month.abb,
  Value1 = 1:12,
  Metric1 = 2:13) 
```

```{r }
sample_data %>% 
  ggplot(aes(x = Month, y = Value1))
#prints empty chart, we haven't specified geom yet
#order of months is incorrect
```

```{r}
sample_data <- tibble(
  Month = month.abb,
  Value1 = 1:12,
  Metric1 = sample(1:20, 12)) %>% 
  mutate(Month = factor(Month, levels = month.abb))

sample_data %>% 
  ggplot(aes(x = Month, y = Value1))
#correct order of months
```

```{r}
#point chart
sample_data %>% 
  ggplot(aes(x = Month, y = Value1)) + 
  geom_point()
```

```{r}
plot1 <- sample_data %>% 
  ggplot(aes(x = Month, y = Value1)) + 
  geom_point()

#title and axis labels
plot1 + 
  xlab("Months") + 
  ylab('Economic Growth') + 
  ggtitle('Data Argentina')
```

```{r}
# add group if line
sample_data %>% 
  ggplot(aes(x = Month, y = Metric1, group = 1)) + 
  geom_line()
```

```{r}
#column chart
sample_data %>% 
  ggplot(aes(x = Month, y = Metric1)) + 
  geom_col()
```


**Multiple dimensions**  

```{r}
# point chart
sample_data %>% 
  pivot_longer(cols = c(2,3), names_to = 'Type') %>% 
  ggplot(aes(x = Month, y = value, color = Type)) + 
  geom_point()
```


```{r}
# line chart
sample_data %>% 
  pivot_longer(cols = c(2,3), names_to = 'Type') %>% 
  ggplot(aes(x = Month, y = value, group = Type, color = Type)) + 
  geom_line()
```

```{r}
# column chart
sample_data %>% 
  pivot_longer(cols = c(2,3), names_to = 'Type') %>% 
  ggplot(aes(x = Month, y = value, fill = Type)) + 
  geom_col(position = 'dodge')
```

```{r}
# facet chart
sample_data %>% 
  pivot_longer(cols = c(2,3), names_to = 'Type') %>% 
  ggplot(aes(x = Month, y = value)) + 
  geom_point() + 
  facet_grid(~Type) #specific notation
```


### CPAT DATA & ggplot2

```{r}
data <- openxlsx::read.xlsx('ExampleDataset.xlsx')
```

```{r}
#let's subset data
input_codes <- read.csv('InputCodes.csv', header = F)[,1] %>% as.character()
input_codes
```

```{r}
data_clean <- data %>% 
  as_tibble() %>% 
  filter(Scenario == 'P41') %>% #quick subset
  filter(CPAT.Code %in% input_codes) %>% #empty cols exist
  janitor::remove_empty(which = "cols") #remove empty columns

data_clean %>% 
  head(2) 
```


ggplot requires data in long format  
We use `pivot_longer` from `tidyr` for such transformation

```{r}
data_clean_long <- data_clean %>% 
  pivot_longer(cols = -c(1:5), names_to = 'Year', values_to = 'Price') %>% 
  mutate(Year = as.numeric(Year)) %>% 
  mutate(Price = as.numeric(Price))

data_clean_long %>% 
  head(2) 
```


Plot indicator with faceting as per `CPAT.indicator`

```{r}
data_clean_long %>% 
  ggplot(aes(x = Year, y = Price)) + 
  geom_point() +
  facet_wrap(~CPAT.indicator, scales = 'free') #each plot has own y axis scale
```


Rebase prices using `group_by` and `mutate` to align y axis for all price series.

```{r}
data_clean_long %>% 
  group_by(CPAT.Code) %>% 
  mutate(Price = 100 * Price/first(Price)) %>% #divide current price by first, for each group
  ungroup() %>% 
  ggplot(aes(x = Year, y = Price,color = CPAT.indicator)) + 
  geom_point()
```




